version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8080:8000"
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"
    environment:
      ADMIN_TOKEN: $$argon2id$$v=19$$m=19456,t=2,p=1$$UUZxK1FZMkZoRHFQRlVrTXZvS0E3bHpNQW55c2dBN2NORzdsa0Nxd1JhND0$$cUoId+JBUsJutlG4rfDZayExfjq4TCt48aBc9qsc3UI

  db:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "5555:3306"
    env_file:
      - .env
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/usr/share/nginx/doc

  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "celery -A configs worker -l info"

  redis:
    image: redis:alpine
    env_file:
      - .env
    restart: on-failure
